name: Mathics3 Package Combinatorica (ubuntu)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install OS dependencies
      run: |
        sudo apt-get update -qq && sudo apt-get install -qq liblapack-dev llvm-dev tesseract-ocr remake
    - name: Install Mathics3 with full dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools "mpmath<1.4,>=1.1.0"
        # We can comment out after next Mathics-Scanner release
        # python -m pip install -e git+https://github.com/Mathics3/mathics-scanner#egg=Mathics-Scanner[full]
        # git clone https://github.com/Mathics3/mathics-scanner.git
        # cd mathics-scanner/
        # pip install -e .
        # cd ..
        # git clone https://github.com/Mathics3/mathics-core.git
        # cd mathics-core/
        # remake -x develop
        # remake -x install
        # cd ..
        pip install -e .[dev]

        # python -m pip install Mathics-Scanner[full]
    - name: Test Mathics3 Package Combinatorica
      run: |
        make check
